version: 0.2

phases:
  pre_build:
    commands:
      #- echo "Logging in to Sixt-Payment Docker Registry"
      # docker login -u push $DOCKER_REGISTRY_URL -p $REGISTRY_PUSH_PASSWORD
      - export IMAGE_TAG=$(cat git_hash)
      #- export IMAGE="$DOCKER_REGISTRY_URL/$SERVICE_NAME:$IMAGE_TAG"
      - export ECR_IMAGE="$ECR_URL:$IMAGE_TAG"
      - export ECR_IMAGE_CLAIR="$ECR_URL:latest"
  build:
    commands:
      - echo "Listing directory contents"
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
      - echo $(pwd) && ls -lah **
      - chmod +x docker-entrypoint.sh
      - echo "Building the Docker image..."          
      - docker build -t $SERVICE_NAME .
      #- docker tag $SERVICE_NAME:latest $IMAGE
      - docker tag $SERVICE_NAME:latest  $ECR_IMAGE
      - docker tag $SERVICE_NAME:latest  $ECR_IMAGE_CLAIR
      
  post_build:
    commands:
      #- 'echo "{\"image\": \"$IMAGE\"}" > deploy.json'
      - 'echo "{\"image\": \"$ECR_IMAGE\"}" > deploy.json'
      - echo Build completed on `date +'%s'`
      - echo "Pushing the Docker image..."
      #- docker push $IMAGE
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
      - docker push  $ECR_IMAGE
      - docker push  $ECR_IMAGE_CLAIR
artifacts:
  files:
    - deploy.json
